CREATE VIEW VEMP (                                                
 EMPNO ,                                       
 FIRSTNME ,                           
 MIDINIT ,                
 LASTNAME ,    
 WORKDEPT )                                                       
 AS                                                   
 SELECT ALL EMPNO , FIRSTNME, MIDINIT , LASTNAME, 
 WORKDEPT FROM GNIVET1.EMPLOYEE                                    

